### ISSUE TITLE
Install fails due to "cannot load library 'pango-1.0'"

### ISSUE THREAD

**Issue by RobertAKARobin** [fdemmer/django-weasyprint#38]
I'm using a Mac running v10.15.5 (Catalina). On attempting to install this via `$pipenv install django-weasyprint` I get the following:

```
Installing django-weasyprint…
Adding django-weasyprint to Pipfile's [packages]…
✔ Installation Succeeded 
Pipfile.lock (4b2068) out of date, updating to (e65fa0)…
Locking [dev-packages] dependencies…
Building requirements...
Resolving dependencies...
✘ Locking Failed! 
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/resolver.py", line 807, in <module>
    main()
  File "/usr/local/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/resolver.py", line 802, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system, parsed.write,
  File "/usr/local/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/resolver.py", line 785, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages)
  File "/usr/local/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/resolver.py", line 758, in resolve_packages
    results = clean_results(results, resolver, project)
  File "/usr/local/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/resolver.py", line 640, in clean_results
    entry_dict = translate_markers(entry.get_cleaned_dict(keep_outdated=False))
  File "/usr/local/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/resolver.py", line 239, in get_cleaned_dict
    self.validate_constraints()
  File "/usr/local/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/resolver.py", line 565, in validate_constraints
    constraints = self.get_constraints()
  File "/usr/local/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/resolver.py", line 493, in get_constraints
    pipfile_constraint = self.get_pipfile_constraint()
  File "/usr/local/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/resolver.py", line 507, in get_pipfile_constraint
    return self.constraint_from_parent_conflicts()
  File "/usr/local/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/resolver.py", line 527, in constraint_from_parent_conflicts
    if not p.requirements:
  File "/usr/local/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/resolver.py", line 625, in __getattribute__
    return super(Entry, self).__getattribute__(key)
  File "/usr/local/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/resolver.py", line 370, in requirements
    self.project.environment.get_package_requirements(self.name)
  File "/usr/local/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/environment.py", line 698, in get_package_requirements
    return [self._get_requirements_for_package(p, key_tree) for p in nodes]
  File "/usr/local/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/environment.py", line 698, in <listcomp>
    return [self._get_requirements_for_package(p, key_tree) for p in nodes]
  File "/usr/local/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/environment.py", line 675, in _get_requirements_for_package
    d['dependencies'] = [
  File "/usr/local/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/environment.py", line 676, in <listcomp>
    cls._get_requirements_for_package(c, key_tree, parent=node,
  File "/usr/local/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/environment.py", line 667, in _get_requirements_for_package
    d = node.as_dict()
  File "/usr/local/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/vendor/pipdeptree.py", line 284, in as_dict
    'installed_version': self.installed_version,
  File "/usr/local/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/vendor/pipdeptree.py", line 251, in installed_version
    return guess_version(self.key, self.UNKNOWN_VERSION)
  File "/usr/local/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/vendor/pipdeptree.py", line 123, in guess_version
    m = import_module(pkg_key)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "$MYPROJECT/.venv/lib/python3.8/site-packages/weasyprint/__init__.py", line 440, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "$MYPROJECT/.venv/lib/python3.8/site-packages/weasyprint/css/__init__.py", line 30, in <module>
    from . import computed_values, media_queries
  File "$MYPROJECT/.venv/lib/python3.8/site-packages/weasyprint/css/computed_values.py", line 18, in <module>
    from .. import text
  File "$MYPROJECT/.venv/lib/python3.8/site-packages/weasyprint/text.py", line 259, in <module>
    pango = dlopen(ffi, 'pango-1.0', 'libpango-1.0-0', 'libpango-1.0.so',
  File "$MYPROJECT/.venv/lib/python3.8/site-packages/weasyprint/text.py", line 254, in dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
  File "$MYPROJECT/.venv/lib/python3.8/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "$MYPROJECT/.venv/lib/python3.8/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "$MYPROJECT/.venv/lib/python3.8/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'pango-1.0': dlopen(pango-1.0, 2): image not found.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'pango-1.0'
```

**Comment by fdemmer** [comment]
The installation of [_weasyprint_](https://weasyprint.org/) fails! Please follow their [instructions](https://weasyprint.readthedocs.io/en/latest/install.html#macos) as mentioned in the [README](https://github.com/fdemmer/django-weasyprint#installing).
